version: '3.8'

services:
  nest-app:
    build: .
    container_name: nest_app_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: always
